// Builds the website: the extension's own UI (the files release.yaml ships) plus a web shell, written to dist/.
// One codebase serves both, so a fix lands in the extension and on the web together.
//   node web/build.mjs [outDir]      SITE_URL overrides the public address (default: the GitHub Pages project URL)
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const DEFAULT_SITE = 'https://ravitejakamalapuram.github.io/TeluguPanchangam/';
const EXTENSION_ONLY = new Set(['manifest.json', '_locales']);
const THEME = '#120808';
const DESCRIPTION = 'ఈ రోజు తెలుగు పంచాంగం: తిథి, నక్షత్రం, రాహుకాలం, పండుగలు, రాశి ఫలాలు. ఉచితం, సైన్-అప్ అవసరం లేదు. '
  + "Today's Telugu panchangam, festivals and rasi phalalu for your city. Free, works offline.";

// release.yaml's `include` allowlist is the single list of files the UI needs.
export function releaseIncludes() {
  const lines = fs.readFileSync(path.join(ROOT, 'release.yaml'), 'utf8').split('\n');
  const start = lines.findIndex((l) => /^\s+include:\s*$/.test(l));
  const out = [];
  for (const line of lines.slice(start + 1)) {
    const m = /^\s+-\s+(\S+)\s*$/.exec(line);
    if (!m) break;
    out.push(m[1]);
  }
  return out;
}

const esc = (s) => s.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

function copyRecursive(from, to) {
  if (fs.statSync(from).isDirectory()) {
    fs.mkdirSync(to, { recursive: true });
    for (const name of fs.readdirSync(from)) copyRecursive(path.join(from, name), path.join(to, name));
  } else {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

function listFiles(dir, base = dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    return e.isDirectory() ? listFiles(full, base) : [path.relative(base, full).split(path.sep).join('/')];
  });
}

function headTags(site) {
  return [
    `<meta name="description" content="${esc(DESCRIPTION)}">`,
    `<meta name="theme-color" content="${THEME}">`,
    `<link rel="canonical" href="${esc(site)}">`,
    '<link rel="manifest" href="manifest.webmanifest">',
    '<link rel="icon" href="web/icons/icon-192.png">',
    '<link rel="apple-touch-icon" href="web/icons/icon-192.png">',
    '<meta property="og:type" content="website">',
    '<meta property="og:title" content="శ్రీ తెలుగు పంచాంగం (Telugu Panchangam)">',
    `<meta property="og:description" content="${esc(DESCRIPTION)}">`,
    `<meta property="og:url" content="${esc(site)}">`,
    `<meta property="og:image" content="${esc(site)}web/icons/icon-512.png">`,
    '<meta name="twitter:card" content="summary">',
    '<link rel="stylesheet" href="web/extras.css">',
  ].map((t) => `  ${t}\n`).join('');
}

function serviceWorker(precache, version) {
  return `// Generated by web/build.mjs. Precaches the app so it opens offline; the cache name changes with every build.
const PRECACHE = ${JSON.stringify(precache)};
const CACHE = 'tp-${version}';

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('tp-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Same-origin GETs: the cached copy first, the network for anything else. The panchangam is computed on the device, so there is no API to cache.
self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  // Offline, a page load falls back to the app shell; a script or image that fails must stay a failure, not become HTML.
  const network = () => fetch(request).catch((err) => (request.mode === 'navigate' ? caches.match('./') : Promise.reject(err)));
  event.respondWith(caches.match(request, { ignoreSearch: true }).then((hit) => hit || network()));
});
`;
}

export async function buildWeb({ outDir = path.join(ROOT, 'dist'), siteUrl = process.env.SITE_URL || DEFAULT_SITE, extraFiles = {} } = {}) {
  const site = siteUrl.endsWith('/') ? siteUrl : `${siteUrl}/`;
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  for (const rel of releaseIncludes().filter((p) => !EXTENSION_ONLY.has(p))) copyRecursive(path.join(ROOT, rel), path.join(outDir, rel));
  copyRecursive(path.join(ROOT, 'web/icons'), path.join(outDir, 'web/icons'));
  for (const f of ['extras.js', 'extras.css']) copyRecursive(path.join(ROOT, 'web', f), path.join(outDir, 'web', f));
  for (const [rel, body] of Object.entries(extraFiles)) fs.writeFileSync(path.join(outDir, rel), body);

  const page = fs.readFileSync(path.join(ROOT, 'newtab.html'), 'utf8')
    .replace('</head>', `${headTags(site)}</head>`)
    .replace('</body>', '  <script src="web/extras.js"></script>\n</body>');
  fs.writeFileSync(path.join(outDir, 'index.html'), page);

  fs.writeFileSync(path.join(outDir, 'manifest.webmanifest'), `${JSON.stringify({
    name: 'శ్రీ తెలుగు పంచాంగం',
    short_name: 'పంచాంగం',
    description: DESCRIPTION,
    lang: 'te',
    start_url: './?utm_source=pwa',
    scope: './',
    display: 'standalone',
    background_color: THEME,
    theme_color: THEME,
    icons: [
      { src: 'web/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: 'web/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    ],
  }, null, 2)}\n`);

  fs.writeFileSync(path.join(outDir, 'robots.txt'), `User-agent: *\nAllow: /\n\nSitemap: ${site}sitemap.xml\n`);
  fs.writeFileSync(path.join(outDir, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${esc(site)}</loc></url>\n</urlset>\n`);
  fs.writeFileSync(path.join(outDir, '404.html'), '<!doctype html>\n<meta charset="utf-8">\n<meta http-equiv="refresh" content="0; url=./">\n<title>తెలుగు పంచాంగం</title>\n<a href="./">తెలుగు పంచాంగం</a>\n');
  fs.writeFileSync(path.join(outDir, '.nojekyll'), '');

  // The worker is written last: its cache name hashes everything else, so any change evicts the old cache.
  const files = listFiles(outDir).filter((f) => !['sw.js', '404.html', '.nojekyll', 'robots.txt', 'sitemap.xml'].includes(f));
  const hash = crypto.createHash('sha256');
  for (const f of files.sort()) hash.update(f).update(fs.readFileSync(path.join(outDir, f)));
  const precache = ['./', ...files.filter((f) => f !== 'index.html')];
  fs.writeFileSync(path.join(outDir, 'sw.js'), serviceWorker(precache, hash.digest('hex').slice(0, 10)));
  return { outDir, files: files.length };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { outDir, files } = await buildWeb({ outDir: process.argv[2] ? path.resolve(process.argv[2]) : undefined });
  console.log(`Built ${files} files into ${path.relative(process.cwd(), outDir) || '.'}`);
}
